version: "2"
services:
  tests:
    image: pymountebank-tests
    build:
      context: ./
      dockerfile: containers/tests/Dockerfile

    environment:
      - PYTHONPATH=/apps

    depends_on:
      - mountebank

  tests2:
    image: pymountebank-tests2
    build:
      context: ./
      dockerfile: containers/tests2/Dockerfile

    environment:
      - PYTHONPATH=/apps

    depends_on:
      - mountebank

  mountebank:
    image: expert360/mountebank:1.3.0
    command: ["start", "--mock"]
